apiVersion: v1
kind: Service
metadata:
  name: jetbrains-guide-service
  namespace: jb-guide-prod
spec:
  type: NodePort
  selector:
    app: jetbrains-guide
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
