apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-deployment
  labels:
    env: {{.Values.env}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: jetbrains-guide-{{.Release.Name}}-{{.Values.env}}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 100 | quote }}
      labels:
        app: jetbrains-guide-{{.Release.Name}}-{{.Values.env}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: nginx
          configMap:
            name: {{.Release.Name}}-nginx-conf-cm
        - name: nginx-main
          configMap:
            name: {{.Release.Name}}-nginx-conf-main-cm
      containers:
        - name: {{.Chart.Name}}
          image: "{{.Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              port: 8080
              path: {{.Values.healthCheck}}
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 15
            httpGet:
              port: 8080
              path: {{.Values.healthCheck}}
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 15
          ports:
            - containerPort: 8080
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              name: nginx
              readOnly: true
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx-main
              readOnly: true

