apiVersion: apps/v1
kind: Deployment
metadata:
  name: jetbrains-guide-deployment
  namespace: jetbrains-guide
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jetbrains-guide
  template:
    metadata:
      labels:
        app: jetbrains-guide
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10014
        runAsGroup: 10014
        fsGroup: 10014
      volumes:
        - name: nginx
          configMap:
            name: nginx-conf-cm
        - name: redirect
          configMap:
            name: nginx-conf-redirect-cm
      containers:
      - name: jetbrains-guide
        image: guide:latest
        imagePullPolicy: Never # Make to Always in prod, using local images set to Never
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            port: 80
            path: /guide
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            port: 80
            path: /guide
          initialDelaySeconds: 5
          periodSeconds: 15
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
              - NET_RAW
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
            name: nginx
            readOnly: true

          - mountPath: /etc/nginx/extra/redirect.conf
            subPath: redirect.conf
            name: redirect
            readOnly: true
