apiVersion: apps/v1
kind: Deployment
metadata:
  name: jetbrains-guide-deployment
  namespace: jb-guide-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jetbrains-guide
  template:
    metadata:
      labels:
        app: jetbrains-guide
    spec:
      securityContext:
        runAsUser: 1000
      imagePullSecrets:
        - name: space-registry-jetbrains-guide
      volumes:
        - name: nginx
          configMap:
            name: nginx-conf-cm
      containers:
      - name: jetbrains-guide
        image: registry.jetbrains.team/p/jetbrains-guide/guide-containers/guide-prod-nginx:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
            name: nginx
