apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-jetbrains-guide-service
  labels:
    env: {{.Values.env}}
spec:
  type: NodePort
  selector:
    app: jetbrains-guide-{{.Release.Name}}-{{.Values.env}}
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30004
