apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-cm
  namespace: jb-guide-prod
data:
  default.conf: |
    server {
        listen       8080;
        listen  [::]:8080;
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    
        absolute_redirect off;
   
        include /etc/nginx/extra/redirect.conf;
    
    }
