apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-cm
  namespace: jetbrains-guide
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            expires 30d;
            add_header Cache-Control "public, no-transform";
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
        }
      
        absolute_redirect off;
   
        include /etc/nginx/extra/redirect.conf;
    
    }
