replicaCount: 2
env: "local"

image:
  repository: registry.jetbrains.team/p/jetbrains-guide/guide-containers/guide-prod-nginx
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: [{name: space-registry-jetbrains-guide}]

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
      - NET_RAW

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

guideRedirect: rewrite ^/product(.*)$ /guide/pycharm/tutorials/fastapi-aws-kubernetes/aws_eks/$1 redirect;

